version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "8000:5000"
      - "9443:9443"
    volumes:
      - "./portainer-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy},templatesrv
